### ISSUE TITLE
Unable to add songs after queue is empty

### ISSUE THREAD

**Issue by stefaneng** [CSUN-Comp490/partyq#267] opened 2015-11-29 04:49 UTC
1. Add song to queue
2. Press next
Then I can't add any more songs to the queue
![image](https://cloud.githubusercontent.com/assets/1639487/11455375/223c1026-9611-11e5-95ef-f7c99fc93a2d.png)

**Comment by ak505188** [comment] 2015-11-29 04:52
The bug is when you skip the last song and try to add the same last song. it will appear when you refresh.

It has something to do with how the iframe works.

**Comment by ak505188** [comment] 2015-11-29 04:53
Also, when the next song is a duplicate it will not reload the iframe. Caused by the same thing.

**Comment by ak505188** [comment] 2015-12-18 06:22
Fixed by changes done in soundcloud integration. Not sure how, but it's fixed.

**Closed** 2016-02-04 19:09 UTC
